# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rakshit/Programming/OOP_Course/course_project/DecenTweet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rakshit/Programming/OOP_Course/course_project/DecenTweet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rakshit/Programming/OOP_Course/course_project/DecenTweet/CMakeFiles /home/rakshit/Programming/OOP_Course/course_project/DecenTweet//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rakshit/Programming/OOP_Course/course_project/DecenTweet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named decentweet

# Build rule for target.
decentweet: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 decentweet
.PHONY : decentweet

# fast build rule for target.
decentweet/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/build
.PHONY : decentweet/fast

src/block.o: src/block.cpp.o
.PHONY : src/block.o

# target to build an object file
src/block.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/block.cpp.o
.PHONY : src/block.cpp.o

src/block.i: src/block.cpp.i
.PHONY : src/block.i

# target to preprocess a source file
src/block.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/block.cpp.i
.PHONY : src/block.cpp.i

src/block.s: src/block.cpp.s
.PHONY : src/block.s

# target to generate assembly for a file
src/block.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/block.cpp.s
.PHONY : src/block.cpp.s

src/blockchain.o: src/blockchain.cpp.o
.PHONY : src/blockchain.o

# target to build an object file
src/blockchain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/blockchain.cpp.o
.PHONY : src/blockchain.cpp.o

src/blockchain.i: src/blockchain.cpp.i
.PHONY : src/blockchain.i

# target to preprocess a source file
src/blockchain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/blockchain.cpp.i
.PHONY : src/blockchain.cpp.i

src/blockchain.s: src/blockchain.cpp.s
.PHONY : src/blockchain.s

# target to generate assembly for a file
src/blockchain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/blockchain.cpp.s
.PHONY : src/blockchain.cpp.s

src/consensus.o: src/consensus.cpp.o
.PHONY : src/consensus.o

# target to build an object file
src/consensus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/consensus.cpp.o
.PHONY : src/consensus.cpp.o

src/consensus.i: src/consensus.cpp.i
.PHONY : src/consensus.i

# target to preprocess a source file
src/consensus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/consensus.cpp.i
.PHONY : src/consensus.cpp.i

src/consensus.s: src/consensus.cpp.s
.PHONY : src/consensus.s

# target to generate assembly for a file
src/consensus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/consensus.cpp.s
.PHONY : src/consensus.cpp.s

src/crypto.o: src/crypto.cpp.o
.PHONY : src/crypto.o

# target to build an object file
src/crypto.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/crypto.cpp.o
.PHONY : src/crypto.cpp.o

src/crypto.i: src/crypto.cpp.i
.PHONY : src/crypto.i

# target to preprocess a source file
src/crypto.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/crypto.cpp.i
.PHONY : src/crypto.cpp.i

src/crypto.s: src/crypto.cpp.s
.PHONY : src/crypto.s

# target to generate assembly for a file
src/crypto.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/crypto.cpp.s
.PHONY : src/crypto.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/network.o: src/network.cpp.o
.PHONY : src/network.o

# target to build an object file
src/network.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/network.cpp.o
.PHONY : src/network.cpp.o

src/network.i: src/network.cpp.i
.PHONY : src/network.i

# target to preprocess a source file
src/network.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/network.cpp.i
.PHONY : src/network.cpp.i

src/network.s: src/network.cpp.s
.PHONY : src/network.s

# target to generate assembly for a file
src/network.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/network.cpp.s
.PHONY : src/network.cpp.s

src/transaction.o: src/transaction.cpp.o
.PHONY : src/transaction.o

# target to build an object file
src/transaction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/transaction.cpp.o
.PHONY : src/transaction.cpp.o

src/transaction.i: src/transaction.cpp.i
.PHONY : src/transaction.i

# target to preprocess a source file
src/transaction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/transaction.cpp.i
.PHONY : src/transaction.cpp.i

src/transaction.s: src/transaction.cpp.s
.PHONY : src/transaction.s

# target to generate assembly for a file
src/transaction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/transaction.cpp.s
.PHONY : src/transaction.cpp.s

src/validator.o: src/validator.cpp.o
.PHONY : src/validator.o

# target to build an object file
src/validator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/validator.cpp.o
.PHONY : src/validator.cpp.o

src/validator.i: src/validator.cpp.i
.PHONY : src/validator.i

# target to preprocess a source file
src/validator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/validator.cpp.i
.PHONY : src/validator.cpp.i

src/validator.s: src/validator.cpp.s
.PHONY : src/validator.s

# target to generate assembly for a file
src/validator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decentweet.dir/build.make CMakeFiles/decentweet.dir/src/validator.cpp.s
.PHONY : src/validator.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... decentweet"
	@echo "... src/block.o"
	@echo "... src/block.i"
	@echo "... src/block.s"
	@echo "... src/blockchain.o"
	@echo "... src/blockchain.i"
	@echo "... src/blockchain.s"
	@echo "... src/consensus.o"
	@echo "... src/consensus.i"
	@echo "... src/consensus.s"
	@echo "... src/crypto.o"
	@echo "... src/crypto.i"
	@echo "... src/crypto.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/network.o"
	@echo "... src/network.i"
	@echo "... src/network.s"
	@echo "... src/transaction.o"
	@echo "... src/transaction.i"
	@echo "... src/transaction.s"
	@echo "... src/validator.o"
	@echo "... src/validator.i"
	@echo "... src/validator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

